### ISSUE TITLE
v-and-xCheck.unit.test file line no 26 not read

### ISSUE THREAD

**Issue by venomTK** [Charitha-Prabashwara/lk.nic#5]
` test("Detect generation using 'v' and 'x'.", ()=>{
        for (let i = 0; i < real_nic.length; i++) {
           
            const dataSeparate = real_nic[i].split(':');
            const nicNumber = dataSeparate[0];
            **const inputResult = dataSeparate[1];**
            const generation = dataSeparate[2];

            
            if(generation == "1"){
                const responseOld = new vxCheck(nicNumber);
                expect(responseOld.isOldGeneration()).toBe(true);
            }else if(generation == "2"){
                const responseNew = new vxCheck(nicNumber);
                expect(responseNew.isNewGeneration()).toBe(true);
            }else{
                expect(true).toHaveBeenCalled();
            }
            
        }
    });`

**Comment by Charitha-Prabashwara** [comment]
OK, can you fix that problem?

**Comment by venomTK** [comment]
Yes, I can do it

**Comment by Charitha-Prabashwara** [comment]
ok, please

**Comment by Charitha-Prabashwara** [comment]
thanks.
